#!/usr/bin/env bash


if [ $# -ne 2 ];
then  
  echo "Usage: grade-lab course-name lab-number"
  echo
  echo "lab-number in format 03_01"
  exit 1
fi  

# wrapper script for grading playbook for lab
#

VIRTUALENV=/opt/virtualenvs/venv-grading
FTL_REPO_HOME=/opt/ftl-repo-clone/
COURSE_NAME=$1
LAB_NUMBER=$2

#
# Clean up - next bit is a job for ansible
# 

if [ -f /tmp/error_report.txt ]; 
then
  cp /tmp/error_report.txt /tmp/error_report.txt-previous
fi

# Make sure ansible finds the correct roles if it loads a new ansible.cfg

export ANSIBLE_ROLES_PATH=${FTL_REPO_HOME}/roles:${FTL_REPO_HOME}/roles-ftl-runtime
export FILE=${FTL_REPO_HOME}/courses/${COURSE_NAME}/ansible.cfg

if [ -f $FILE ]; then
   export ANSIBLE_CONFIG=${FILE}
fi

# Activate a protected vurtualenv with all dependencies and it's own ansible

echo "Starting Grading Process"

source ${VIRTUALENV}/bin/activate

( cd ${FTL_REPO_HOME};  ansible-playbook grade_lab.yml              \
  -e @vars/global_vars.yml                                          \
  -e course_name=${COURSE_NAME}                                     \
  -e lab_number=${LAB_NUMBER} -vv > /tmp/opentlc_grader_log 2>&1 )

# Output the error report

cat /tmp/error_report.txt

