---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
  tasks:
    ## setup common password
    - name: set common password
      set_fact:
        common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"
    
    - debug: var=common_password

    ## Result for Gitlab webhook #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: common_password is defined

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: common_password is not defined

    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if common password is defined"

    - name: get api for devclsuter
      k8s_info:
        kind: ManagedCluster
        api_version: clusterview.open-cluster-management.io/v1
        name: aws-dev-cluster
        namespace: open-cluster-management
      register: r_aws_dev_cluster


    - name: get api for devclsuter
      k8s_info:
        kind: ManagedCluster
        api_version: clusterview.open-cluster-management.io/v1
        name: aws-prod-cluster
        namespace: open-cluster-management
      register: r_aws_prod_cluster

    - set_fact:
        _aws_dev_cluster_api: "{{ r_aws_dev_cluster.resources.0.spec.managedClusterClientConfigs.0.url }}"
        _aws_prod_cluster_api: "{{ r_aws_prod_cluster.resources.0.spec.managedClusterClientConfigs.0.url }}"

    - debug: var=_aws_dev_cluster_api
    - debug: var=_aws_prod_cluster_api

    - name: Log into AWS OCP4 Dev Cluster
      k8s_auth:
        host: "{{ _aws_dev_cluster_api }}"
        username: "admin"
        password: "{{ common_password }}"
        validate_certs: false
      register: __r_aws_dev_cluster
      retries: 240
      delay: 15
      until:
      - __r_aws_dev_cluster.k8s_auth.api_key is defined

    - name: Log into AWS OCP4 Prod Cluster
      k8s_auth:
        host: "{{ _aws_prod_cluster_api }}"
        username: "admin"
        password: "{{ common_password }}"
        validate_certs: false
      register: __r_aws_prod_cluster
      retries: 240
      delay: 15
      until:
      - __r_aws_prod_cluster.k8s_auth.api_key is defined

    - name: Get Hub Argocd Route
      k8s_info:
        host: "{{ __r_aws_hub_cluster.k8s_auth.host }}"
        username: "{{ __r_aws_hub_cluster.k8s_auth.username }}"
        api_key: "{{ __r_aws_hub_cluster.k8s_auth.api_key }}"
        validate_certs: false
        kind: Route
        name: openshift-gitops-server
        namespace: openshift-gitops
      register: r_hub_argocd
      retries: 60
      delay: 5
      until: r_hub_argocd.resources | length > 0
    
    - debug: var=r_dev_argocd.resources
...