---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    ## setup common password
    - include_tasks: auth_tasks.yml
    
    ## Result for Gitlab webhook #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: common_password is defined

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: common_password is not defined

    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if common password is defined"

    - name: Get Hub Argocd Route
      k8s_info:
        host: "{{ __r_aws_dev_cluster.k8s_auth.host }}"
        username: "{{ __r_aws_dev_cluster.k8s_auth.username }}"
        api_key: "{{ __r_aws_dev_cluster.k8s_auth.api_key }}"
        validate_certs: false
        kind: Route
        name: openshift-gitops-server
        namespace: openshift-gitops
      register: r_dev_argocd
      retries: 60
      delay: 5
      until: r_dev_argocd.resources | length > 0
    
    - debug: var=r_dev_argocd.resources
...