---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
  tasks:
    - name: set common password
      set_fact:
        common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"
    
    - debug: var=common_password

##### Result for Gitlab webhook #####
    - name: "Success - set fact"
      set_fact:
        success: true
      when: common_password is defined

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: common_password is not defined

    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Check if common password is defined"

...