---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - solve_lab__post_check
  tasks:
    - name: Included authentication tasks
      include_tasks: ../auth_tasks.yml

    ## Gitea PR merge
    - name: Get Hub gitea route
      k8s_info:
        kind: Route
        name: gitea
        namespace: gitea
      register: r_hub_gitea
      retries: 60
      delay: 5
      until: r_hub_gitea.resources | length > 0

    - name: List gitlab webhook
      uri: 
        url: https://{{ r_hub_gitea.resources.0.spec.host }}/api/v1/repos/dev-user/devsecops-validated-pattern/pulls
        user: dev-admin
        password: openshift
        method: GET
        body_format: json
        force_basic_auth: true
        validate_certs: false
        status_code: 200
      register: r_hub_gitea_pr_list

    - name: List gitlab webhook
      uri: 
        url: https://{{ r_hub_gitea.resources.0.spec.host }}/api/v1/repos/dev-user/devsecops-validated-pattern/pulls/1/merge
        user: dev-admin
        password: openshift
        method: POST
        body_format: json
        force_basic_auth: true
        validate_certs: false
        status_code: 200
        body: >-
          {
            "Do": "merge",
            "MergeMessageField": "Looks Good",
            "delete_branch_after_merge": true,
            "force_merge": true
          }

      