== Overview

FTL (Finish the Labs) provides a platform to both grade and solve student labs. In addition it provides hooks to update the students results to the LMS. This guide covers the topic of how to create a series of lab grading playbooks for a course.

Before we look at creating *grading* playbooks it is valuable to understand the typical workflow of a student grading a lab.

=== Student Workflow

. Student provisions lab as instructed via http:labs.opentlc.com
** *FTL* is inserted automatically at provisioing time
** *FTL* is fully provisioned with necessary meta-data and utilities
. Student works through lab
. Student is prompted at end of lab to grade the lab via a simple copy and paste in terminal window e.g.
+
[source,bash]
----
$ grade_lab ansible_foundations 03_01
----
+
NOTE:  syntax: `<grade_lab command> <course_name> <lab_and_sub-lab_number`
e.g. Grade the first lab in *Ansible Foundations Module 3 
. On success:
** Student informed
** *LMS* Updated (As of 2019-04-26 roles is called but API logic incomplete"
. On failure:
** Student is informed
** *LMS* Updated (As of 2019-04-26 roles is called but API logic incomplete"
+
NOTE: Student can try repeatedly until success is achieved.

On completion of a lab the student will copy and paste the lab checking command which will wrap the `lab_grading` playbook which will:

=== Notes

NOTE: In version 1.0 no attempt is made to generate a score. A student either passes or fails.

This guide focusses on Step 3 above and how to successfully create grading (and solving) playbooks

* *grading* playbooks: checks a students work by validating key steps have been completed
* *solver* playbooks: solves an entire lab
** Can be called sequentially i.e. each lab in a course, to validate a lab infrastructure is valid

=== Instructor Workflow
.Creating grading and solving playbooks


Identify the key tasks to validate in a student lab. In a lab of any complexity it can be considered a good practice to check at multiple stages the students progress. Just testing the final stage or end result, for example testing a URI for an expected response doesn't allow detailed feedback to the student.

Test critical stages.

TIP: Whilst a complex lab may be easy to test by the response for say the final application, upon student failure
o
=== Structure

At the root level of the FTL repo the directory `courses/` is used to hold each course in a course directory. *All* course grading content including lab specific roles should be encapsulated in your course directory which you can create here.. _(For those familiar with link:https://github.com/redhat-cop/agnosticd/tree/development/ansible[Ansible Agnostic Deployer] this pattern is similar to its `configs`)_

[source,bash]
----
courses
├── ansible_engine_foundations
├── ansible_implementation_part1
├── ansible_implementation_part2
├── ansible_integrations
├── ansible_tower_implementation
├── ocp_implementation
├── ...
----

Each *course* directory e.g. `courses/ansible_engine_foundations/` contains all playbooks, metadata (e.g. inventory files, lab specific roles etc), and sub directories for each lab.

[source,bash]
----
courses/ansible_engine_foundations
├── ansible.cfg
├── lab_03_01
│   ├── grade_lab.yml
│   └── solve_lab.yml
├── lab_04_01
│   ├── grade_lab.yml
│   └── solve_lab.yml
└── lab_05_01
    ├── grade_lab.yml
    └── solve_lab.yml
----

==== `ansible.cfg`

A root level `ansible.cfg` is provided and should not be modified. At runtime if the relevant course directory can be provided and is consumed by the grader and solver playbook. This allows the author of graders fine grained control of their environment if necessary. 

NOTE: In addition it allows the reuse of existing inventory files on the the grader host

==== Precedence of `ansible.cfg` 

Highest to lowest

. lab directory: `courses/ansible_engine_foundations/lab_03_01/ansible.cfg`
. course directory:  `courses/ansible_engine_foundations/ansible.cfg`
. root FTL directory `ansible.cfg`

=== Dealing with Inventory

grader and solver playbooks 
