:toc:

== Overview

This document takes a developer through the entire series of steps to create the *grader* for the course *Ansible Implementation* including testing and merging back into the master branch.

=== Planning Stage

Before starting to code it is worthwhile to understand the nature of the environment you are grading. In the case of our example *Ansible Implementation* this is a traditional infrastructure type course with a `bastion` host and a number of instances which it will run the graders against e.g. "do the web servers have apache running".

You need to consider where *FTL* will be installed. Typically this would be on the `bastion` or `workstation` machine where the student does most of their work. This machine will be the *grader host*

As we go through the walkthrough we will discuss issues like *inventory* etc and student and lab metadata e.g. opentlc user name and GUID.

=== Setup

Setup your development machine if you haven't already done so.

. Clone FTL to your local machine
+
[source,bash]
----
git clone https://github.com/redhat-gpe/FTL.git
----
. Install Ansible using your tool of choice `yum`, `brew`, `pip`
+
[source,bash]
----
pip install ansible
----

////

Come back here if any other dependencies need to be added - like boto

////

=== Setup your lab grader branch and environment

Avoid working directly on `master`, each lab grader should be *developed* on it's own branch and finally merged via a PR. During development you will be able to install and test your branch on your target labs.

. Create a, meaningful, branch name e.g.: `grader_course_name` (or for solvers solver_course_name)
+
[source,bash]
----
git branch grader-ansible-implementation
git checkout grader-ansible-implementation
----
. Create your course directory 
+
All graders and solvers live in the *courses* directory. If you are familiar with `agnosticd` this is similar to the pattern used by `configs`
From your repos home `FTL` directory create your course sub-directory by copying the sample skeletos provided.

+
[source,bash]
----
.
├── README.adoc
├── ansible.cfg
├── courses                     <1>
├── devel
├── docs
├── main.yml
├── roles
└── vars
----
+
1. All courses and their graders, solvers etc live in the `courses` sub-directory
** External courses can be supported and a `ftl_run_load_external_course` role is *planned*

+
NOTE: The `courses` sub-directory has, currently, 1 example course skeleton.`EXAMPLE_COURSE_SKELETON`

+
[source,bash]
----
courses
├── EXAMPLE_COURSE_SKELETON
├── ansible_foundations
├── ansible_implementation_part1
├── archive
├── ocp_implementation
└── ocp_operations
----

`EXAMPLE_COURSE_SKELETON`, this contains a simple sample course :
[source,bash]
----
.
├── README.adoc
├── ansible.cfg
├── grader-inventory
└── lab_01_01
    ├── grade_lab.yml
    ├── roles
    └── solve_lab.yml
----



=== Creating your First Grader

. If you have not already done so clone the FTL repo to your development machine
+
[source,bash]
----
git clone https://github.com/redhat-gpte-devopsautomation/FTL.git
----

. Create your developer branch

+
[source,bash]
----
git checkout -d grader_ansible_implementation_part1
----

. Create the basic structure for the course
+
[source,bash]
----
cd FTL/courses
cp -R EXAMPLE_COURSE_SKELETON ansible_implementation_part1
----

. Explore your basic course skeleton

[source,bash]
----
$ cd ansible_implementation_part1
$ tree
.
├── ansible.cfg                       <1>
├── grader_inventory                  <2>
└── lab_01_01                         <3>
    ├── grade_lab.yml                 <4>
    ├── roles
    └── solve_lab.yml

----
+
. My file


=== Stage 1: Create your Inventory and `ansible.cfg` - if necessary.

This particular course *Ansible Implementation Part1* is an infrastructure based course, i.e. it works with instances, or VMs, typically deployed on *AWS*. So we need an *inventory* and an `ansible.cfg` in the root directory of the *course* i.e.`FTL/courses/ansible_implementation_part1`.


. The default `ansible.cfg` from the 


