== Overview: Grader Roles

In the FTL root `roles` directory a number of *grader roles * have been provided. These test common scenarios and are designed to allow grader playbooks for labs to be written easily and simply.

Grader roles include their own logging so a simple lab grader can simply call 1 or more grader roles in sequence to grade a lab.

=== Example grader roles
grader_check_file_exists
grader_check_ocp_node_exists
grader_check_ocp_route_exists
grader_check_ocp_svc_exists
grader_check_package_installed
grader_check_service_enabled
grader_check_service_started
grader_check_uri_response
grader_check_user_does_not_exist
grader_check_user_exists

=== Simple Walk Through

In the sample below 2 convenience roles are called using a common pattern

[source,yaml,linenums]
----

---
- name: Grade lab 03 01 of Ansible Engine Foundations
  hosts: web
  gather_facts: false
  become: true

  roles:      # All lab tests go here

    - name: Section 6.4.1, Check student has installed Apache
      role: grader_check_package_installed
      vars:
        task_description_message: Install Apache, httpd, package
        package: httpd

    - name: Section 6.4.2, Check student has running Apache
      role: grader_check_service_started
      vars:
        task_description_message: Start Apache, httpd, Service
        service: httpd

    - name: Section 6.4.3, Check student has enabled Apache
      role: grader_check_service_enabled
      vars:
        task_description_message: Enable Apache, httpd, at boot
...
