:toc:

== Overview

This document takes a developer through the entire series of steps to create the *grader* for the course *Ansible Implementation* including testing and merging back into the master branch.

=== Planning Stage

Before starting to code it is worthwhile to understand the nature of the environment you are grading. In the case of our example *Ansible Implementation* this is a traditional infrastructure type course with a `bastion` host and a number of instances which it will run the graders against e.g. "do the web servers have apache running".

You need to consider where *FTL* will be installed. Typically this would be on the `bastion` or `workstation` machine where the student does most of their work. This machine will be the *grader host*

s we go through the walkthrough we will discuss issues like inventory etc and student and lab metadata e.g. opentlc user name and GUID.


=== Setup

Setup your development machine if you haven't already done so.

. Clone FTL to your local machine
+
[source,bash]
----
git clone https://github.com/redhat-gpe/FTL.git
----
. Install Ansible using your tool of choice `yum`, `brew`, `pip`
+
[source,bash]
----
pip install ansible
----

////

Come back here if any other dependencies need to be added - like boto

////

=== Setup your lab grader branch and environment

Avoid working directly on `master`, each lab grader should be *developed* on it's own branch and finally merged via a PR. During development you will be able to install and test your branch on your targer labs.

. Create a, meaningful, branch name e.g.: `grader_course_name` (or for solvers solver_course_name)
+
[source,bash]
----
git branch grader-ansible-implementation
git checkout grader-ansible-implementation
----
. Create your course directory
+
All graders and solvers live in the courses directory. If you are familair with `agnosticd` this is similar to the pattern used by `configs`
From your repos homw directory `FTL` create your course sub-directory: e.g.

+
[source,bash]
----
cd FTL/courses
mkdir ansible_implementation_part1
cd ansible_implementation_part1
----

=== Stage 1: Create your Inventory and `ansible.cfg`

This particualr course *Ansible Implementation Part1* is an infrastructure based course, i.e. it works with instances, or VMs, typically deployed on *AWS*.






