# vim: set ft=ansible
---
- name: Reset lab App Management Basics of cp-ocp-admin-storage workshop
  hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - name: login as system:admin
    command: oc login -u system:admin

  - name: remove the volume from the app
    command: oc set volume -n app-management dc/mapit --remove --name=mapit-storage

  - name: delete the pvc that was created
    command: oc delete -n app-management pvc mapit-storage
