# vim: set ft=ansible
---
- name: Solve lab App Storage Basics of cp-ocp-admin-storage workshop
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - role: '../roles/cp-ocp-admin-storage-prereqs'
  tasks:

  - name: check for the app management project (it's a prereq for this lab)
    k8s_facts:
      api_version: v1
      kind: Namespace
      name: app-management
    register: namespace_exists
    failed_when:
      - namespace_exists.resources | length | int != 1

  - name: add storage to the app
    shell: 'oc set volume dc/mapit --add --name=mapit-storage -t pvc --claim-mode=ReadWriteOnce --claim-size=1Gi --claim-name=mapit-storage --mount-path=/app-storage'

  - name: check that we ended up with a volume
    k8s_facts:
      api_version: apps.openshift.io/v1
      kind: DeploymentConfig
      namespace: app-management
      name: mapit
    register: mapit_dc
    failed_when:
      - mapit_dc.resources[0].spec.template.spec.volumes | length | int != 1

  - name: make sure the pvc eventually binds
    k8s_facts:
      api_version: v1
      kind: PersistentVolumeClaim
      namespace: app-management
      name: mapit-storage
    register: pvc
    until:
      - pvc.resources | length | int > 0
      - pvc.resources[0].status is defined
      - pvc.resources[0].status.phase is defined
      - pvc.resources[0].status.phase == "Bound"
    delay: 30
    retries: 10