---
- name: Grade OpenShift Advanced Day 2 Operations ILT Final Lab
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks: 
  # Namespace backend-dev
  - name: Check LimitRange limits in namespace backend-dev
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: LimitRange
      resource_name: limits
      resource_namespace: backend-dev
      resource_definition_checks:
      - error_message: "LimitRange limits does not have a limit of 2 CPUs in namespace backend-dev"
        json_query: "spec.limits[0].max.cpu"
        value: "2"
      - error_message: "LimitRange limits does not have a limit of 4Gi memory in namespace backend-dev"
        json_query: "spec.limits[0].max.memory"
        value: "4Gi"
      - error_message: "LimitRange limits is not setup for Pods in namespace backend-dev"
        json_query: "spec.limits[0].type"
        value: "Pod"
      task_description_message: "Check LimitRange limits in project backend-dev."
      student_error_message: "LimitRange limits is not set up correctly in project backend-dev."

  - name: Check ResourceQuota quota in namespace backend-dev
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: ResourceQuota
      resource_name: quota
      resource_namespace: backend-dev
      resource_definition_checks:
      - error_message: "ResourceQuota quota does nothave 40 ConfigMaps in namespace backend-dev"
        json_query: "spec.hard.configmaps"
        value: "40"
      - error_message: "ResourceQuota quota does not have 5 PersistentVolumeClaims in namespace backend-dev"
        json_query: "spec.hard.persistentvolumeclaims"
        value: "5"
      - error_message: "ResourceQuota quota does not have 5 Pods in namespace backend-dev"
        json_query: "spec.hard.pods"
        value: "5"
      - error_message: "ResourceQuota quota does not have 40 Secrets in namespace backend-dev"
        json_query: "spec.hard.secrets"
        value: "40"
      - error_message: "ResourceQuota quota does not have 5 cpu requests in namespace backend-dev"
        json_query: "spec.hard.requests.cpu"
        value: "5"
      - error_message: "ResourceQuota quota does not have 10Gi Memory requests in namespace backend-dev"
        json_query: "spec.hard.requests.memory"
        value: "10Gi"
      - error_message: "ResourceQuota quota does not have 10Gi storage requests in namespace backend-dev"
        json_query: "spec.hard.requests.storage"
        value: "10Gi"
      task_description_message: "Check ResourceQuota quota in project backend-dev."
      student_error_message: "ResourceQuota quota is not set up correctly in project backend-dev."

  # Namespace frontend-dev
  - name: Check LimitRange limits in namespace frontend-dev
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: LimitRange
      resource_name: limits
      resource_namespace: frontend-dev
      resource_definition_checks:
      - error_message: "LimitRange limits does not have a limit of 2 CPUs in namespace frontend-dev"
        json_query: "spec.limits[0].max.cpu"
        value: "2"
      - error_message: "LimitRange limits does not have a limit of 4Gi memory in namespace frontend-dev"
        json_query: "spec.limits[0].max.memory"
        value: "4Gi"
      - error_message: "LimitRange limits is not setup for Pods in namespace frontend-dev"
        json_query: "spec.limits[0].type"
        value: "Pod"
      task_description_message: "Check LimitRange limits in project frontend-dev."
      student_error_message: "LimitRange limits is not set up correctly in project frontend-dev."
