- name: Solve Lab03 if asked
  hosts: bastions
  become: yes
  gather_facts: no
  tasks:
    - name: Clone Git repo
      git: 
        repo: https://github.com/redhat-gpte-devopsautomation/ansible_implementation_part2_solve.git
        dest: /root/ansible_implementation_part2_solve
        force: yes

    - name: Execute remote web_playbook
      shell: ansible-playbook web_playbook.yml 
      args:
        chdir: /root/ansible_implementation_part2_solve