---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - grade_lab_pre_check
  tasks:
    - name: Included authentication tasks
      include_tasks: ../auth_tasks.yml

    - name: Included authentication tasks
      include_tasks: ../auth_tasks.yml
      loop:
      - database
      - winweb01
      - winweb02
...