---
- name: Run grader
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - grade_lab_pre_check
  tasks:
    - name: Included authentication tasks
      include_tasks: ../auth_tasks.yml

    - name: Included authentication tasks
      include_tasks: ../check_virtual_machines.yml
      loop:
      - database
      - winweb01
      - winweb02

    - name: Retrieve Ingress config
      k8s_info:
        api_version: config.openshift.io/v1
        kind: Ingress
        name: cluster
      register: r_ingress_config

    - name: "Set webapp url"
      set_fact:
        ocp4_virt_on_rosa_route_webapp_url: "https://{{ ocp4_virt_on_rosa_route_webapp_name }}-{{
          ocp4_virt_on_rosa_vm_namespace }}.{{
          r_ingress_config.resources[0].spec.domain }}"

    - name: Check if webapp is deployed
      ansible.builtin.uri:
        url: "{{ ocp4_virt_on_rosa_route_webapp_url }}"
        method: GET
      register: r_webapp

    - name: "Success - set fact"
      set_fact:
        success: true
      when: r_webapp.status == 200

    - name: "No Success - set fact"
      set_fact:
        success: false
      when: r_webapp.status != 200

    - name: Import logging role
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        task_description_message: "Checking if webapp is deployed at {{ ocp4_virt_on_rosa_route_webapp_url }}"
...