---
- name: Grade lab 03 01 of Ansible Implementation
  hosts: apps
  gather_facts: false

  roles:      # All lab tests go here

    - name: Section 5
      import_role: 
        name: grader_check_package_installed
      vars:
        package: httpd
        task_description_message: Check package httpd installed 

    - name: Section 5
      import_role: 
        name: grader_check_service_started
      vars:
        service: httpd
        task_description_message: Check service httpd started

    - name: Section 5
      import_role: 
        name: grader_check_service_enabled
      vars:
        service: httpd
        task_description_message: Check service httpd enabled
...
