---
- name: Grade Advanced Application Deployment with Red Hat OpenShift ILT Final Lab
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks: 
  - name: Retrieve PREFIX from the Environment
    set_fact:
      prefix: "{{ lookup('env', 'PREFIX') }}"
  - name: Check PREFIX
    when: prefix | default("") | length == 0
    block:
    - name: Log error 
      import_role:
        name: ftl_run_log_grade_to_log
      vars:
        grader_output_message: "FAIL: PREFIX environment variable is not set."
        success: false
    - name: Abort
      fail:
        msg: PREFIX environment variable is not set.
  - name: Log PREFIX
    when: prefix | default("") | length > 0
    import_role:
      name: ftl_run_log_grade_to_log
    vars:
      grader_output_message: "PASS: PREFIX environment variable is set to {{ prefix }}."
      success: true

  - name: Delete all previous pipeline runs
    shell: "tkn pr delete --all --force -n {{ prefix }}-pipeline"
    ignore_errors: true

  - name: Run pipeline for coffee-shop
    shell: >-
      tkn pipeline start build-and-deploy-quarkus-application
      --use-param-defaults
      --param DEPLOY_SERVERLESS=false
      --param APP_NAME=coffee-shop
      --param KUSTOMIZE_GIT_CONTEXT_DIR=coffee-shop-kustomize/coffee-shop
      --param KUSTOMIZE_GIT_FILE_NAME=overlays/production/deployment-patches.yaml
      --workspace name=app-source,claimName=workspace-pvc
      --workspace name=maven-settings,emptyDir=
      --workspace name=images-url,emptyDir=
      --pod-template=$HOME/coffee-shop-final-lab/coffee-shop-pipeline/pod-template.yaml
      --showlog
      -n {{ prefix }}-pipeline
    register: r_run_coffeeshop_pipeline

  - name: Retrieve image tag for coffee-shop from pipeline
    debug:
      msg: tbd
  - name: Check that coffee-shop application is using latest image tag
    debug:
      msg: tbd

  - name: Run pipeline for barista
    debug:
      msg: tbd
  - name: Retrieve image tag for barista from pipeline
    debug:
      msg: tbd
  - name: Check that barista application is using latest image tag
    debug:
      msg: tbd

  # - name: "Check that tasks route in {{ guid }}-tasks-prod points to the Green Service"
  #   include_role:
  #     name: grader_check_ocp_resource
  #   vars:
  #     task_description_message: "Check that tasks route in {{ guid }}-tasks-prod points to the green service"
  #     resource_api_version: route.openshift.io/v1
  #     resource_kind: Route
  #     resource_name: tasks
  #     resource_namespace: "{{ guid }}-tasks-prod"
  #     resource_definition_checks:
  #     - error_message: Tasks route does not point to tasks-green service.
  #       json_query: "spec.to.name"
  #       value: "tasks-green"
