---
- name: Solve the OCP4 on OpenStack limit ranges and Horizontal Pod Autoscaler Lab
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/openstack-upi/auth/kubeconfig"
    INFRA_ID: "INFRA_ID=$(jq -r .infraID {{ lookup('env', 'HOME') }}/openstack-upi/metadata.json)"

  tasks:
    - name: Set python version
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      tags: test

    - name: Delete previous project
      k8s:
        name: my-hpa
        kind: Namespace
        state: absent
        wait: yes

    - name: Create new project
      k8s:
        name: my-hpa
        kind: Namespace 
        state: present
      
    - name: Deploy application
      command: "oc new-app quay.io/gpte-devops-automation/pod-autoscale-lab:rc0 --name=pod-autoscale -n my-hpa"

    - name: Expose service
      command: "oc expose svc/pod-autoscale -n my-hpa"

    - name: Create LimitRange
      k8s:
        state: present
        definition:
          kind: LimitRange
          apiVersion: v1
          metadata:
            name: limits
            namespace: my-hpa
          spec:
            limits:
            - type: Pod
              max:
                cpu: 100m
                memory: 750Mi
              min:
                cpu: 10m
                memory: 5Mi
            - type: Container
              max:
                cpu: 100m
                memory: 750Mi
              min:
                cpu: 10m
              memory: 5Mi
              default:
                cpu: 50m
                memory: 100Mi

    - name: Create Horizontal Pod Autoscaler
      k8s:
        state: present
        definition:
          kind: HorizontalPodAutoscaler
          apiVersion: autoscaling/v2beta2
          metadata:
            name: pod-autoscale
            namespace: my-hpa
          spec:
            maxReplicas: 5
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: pod-autoscale
            targetCPUUtilizationPercentage: 60

- name: Solve OCP4 Custom HPA
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/openstack-upi/auth/kubeconfig"
    INFRA_ID: "INFRA_ID=$(jq -r .infraID {{ lookup('env', 'HOME') }}/openstack-upi/metadata.json)"

  tasks:
    - name: Create Prometheus project
      k8s:
        state: present
        name: my-prometheus
        kind: Namespace

    - name: Creating OperatorGroup
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: prometheus
            namespace: my-prometheus
          spec:
            targetNamespaces:
            - my-prometheus

    - name: Create subscription object
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: prometheus
            namespace: my-prometheus
          spec:
            channel: beta
            name: prometheus
            source: community-operators
            sourceNamespace: openshift-marketplace
