:toc:

== Overview


=== Pushing your development code

To speed up the development cycle it is possible to push changes in FTL directly
to your development grader host without having to redeploy. The example given
below is for a labs.opentlc.com deployed `three-tier-app` config.

==== Steps

. Work from the development directory


. Install the `ftl-injector` role locally

+
[source,bash]
----
ansible-galaxy install git+https://github.com/redhat-gpte-devopsautomation/ftl-injector.git
----
. Create an appropriate inventory

NOTE: A simple pattern, that avoids needless updating of inventory files is to
export a shell environmental variable e.g. `export GRADER_HOST=<GUID>`.

A sample inventory file is provided and enables by `ansible.cfg`


[source,bash]
----
$ ansible-playbook utilities/setup-grading-host.yml \     <1>
  -i utilities/inventories/ansible-foundations-test \     <2>
  -e @utilities/test-data/sample-vars.yml           \     <3>
  -e @~/secret.yml                                        <4>
----

. PLaybook calling the roles to:
* Setup the virtualenv on the grading host `ftl_run_create_grading_virtualenv`
* Setup the FTL repo and utilitis on grading host `ftl_run_setup_grading_host`
. Your test *inventory*, for example
+
[source,bash]
----
[grading_host]
grader_host

[grading_host:vars]
ansible_host                    = 3.213.167.74
ansible_user                    = student1
ansible_ssh_pass                = ansible

